### ISSUE TITLE
Question about retriever..

### ISSUE THREAD

**Issue by gabinguo** [rsvp-ai/bertserini#12]
A silly question about the retriever part:

I was trying to index the Wikipedia dump in paragraph-level as you did. And in the paper, you mentioned that you got 29.5M paragraphs, but instead I got 33.3M paragraphs. So, I would like to ask if you did some special filter setting when you split the article into paragraphs or just easily split them by `article.split("\n")`

Thanks

**Comment by amyxie361** [comment]
Hi, we use "\n\n"to split the paragraphs. And we use 2016-12-21 Wikipedia dump and follow the preprocess [here](https://github.com/facebookresearch/DrQA#wikipedia).

**Comment by gabinguo** [comment]
> Hi, we use "\n\n"to split the paragraphs. And we use 2016-12-21 Wikipedia dump and follow the preprocess [here](https://github.com/facebookresearch/DrQA#wikipedia).

Exactly what I am looking for. Thanks a lot.
