### ISSUE TITLE
How to build index for Chinese corpus?

### ISSUE THREAD

**Issue by a5038c** [rsvp-ai/bertserini#13]
Now i want to try to build index for Chines corpus other than your pre-built Chinese Wiki index. From your document, i should use Anserini's script bin/IndexConnection. But i think that script is only used to build index for English corpus. Is there any way to build index for Chinese corpus? Thanks a lot!

**Comment by amyxie361** [comment]
You can use the ```-language zh``` argument to index Chinese corpus. 
Please refer to this PR of anserini: https://github.com/castorini/anserini/pull/804
