### ISSUE TITLE
Code freeze on inference 

### ISSUE THREAD

**Issue by code158m** [rsvp-ai/bertserini#14]
Hi, 
When I run the [inference code](https://github.com/rsvp-ai/bertserini/blob/development/bertserini/experiments/inference.py) , it freezes almost each time. No error comes, but the code freezes randomly. 
Is this a common issue? Any suggestions on how to fix this?
Thanks!

**Comment by amyxie361** [comment]
Might related to the transformers version issue. Try roll back it to transformers==3.4.0
