### ISSUE TITLE
dependencies update

### ISSUE THREAD

**Issue by ncthuan** [rsvp-ai/bertserini#15]
I was installing and running the code on Google Colab and ran into some dependency issue. 

- utils.py uses **zhon** which is not in the **requirement.txt** file yet. So i had to install it manually
- torch is reinstalled,  from 1.8.1 back to 1.5.1, which take more time and resources

So please consider updating the requirement.txt file

**Comment by lintool** [comment]
Thanks for the issue!

Just FYI - BERTserini has been superseded by more recent toolkits such as Facebook's DPR: https://github.com/facebookresearch/DPR

**Comment by ncthuan** [comment]
Yes, I agree. DPR is a great work.

But as a student learning about open domain QA, for me is still important to start off from the very first work, like DrQA(2017) and learn about the innovations over the years. 

Thanks for the work of BERTserini, i learned a lot.
I'm closing this now.
