### ISSUE TITLE
Error while running the simple example in README

### ISSUE THREAD

**Issue by raj26000** [rsvp-ai/bertserini#16]
Hi, I tried cloning the repo in google colab and running the example given in README. However, I encounter a persistent error in the following line: (No Module error)
`from transformers.tokenization_bert import BasicTokenizer`
from this file: [https://github.com/rsvp-ai/bertserini/blob/development/bertserini/utils/utils_squad.py]()

Could anyone help?

**Comment by riccardobosio** [comment]
Try to put transformers==3.5 in the requirements.txt. I used it and it worked.
