### ISSUE TITLE
bertsirini.experiments.inference

### ISSUE THREAD

**Issue by MudassarHussainAwan** [rsvp-ai/bertserini#18]
!python -m bertserini.experiments.inference --dataset_path data/dev-v2.0.json \
                                           --index_path indexes/lucene-index.enwiki-20180701-paragraphs \
                                           --model_name_or_path rsvp-ai/bertserini-bert-base-squad \
                                           --output squad_bert_base_pred.json \
                                           --topk 10 --tokenizer_name rsvp-ai/bertserini-bert-base-squad 

The code raises TypeError :  TextInputSequence must be str.

**Comment by amyxie361** [comment]
see https://github.com/rsvp-ai/bertserini/issues/19#issuecomment-1057662148
