### ISSUE TITLE
Error when running the example in README

### ISSUE THREAD

**Issue by QinBixuan** [rsvp-ai/bertserini#19]
Hi! I run the sample in README using Option2 (the local context), with Transformers 4.16.2. 
I encountered an Error:  TypeError: TextInputSequence must be str
It happened in line `candidates = bert_reader.predict(question, contexts)`. Could someone help with it? Thank you a lot in advance.

**Comment by amyxie361** [comment]
Just updated the development branch.
Please roll back to transformers==3.4.0 (for my case it works but haven't verified for other versions).
