### ISSUE TITLE
PyPI instructions

### ISSUE THREAD

**Issue by lintool** [rsvp-ai/bertserini#6]
Hi @MXueguang I see that we've already published on `PyPI` - great!
https://pypi.org/project/bertserini/

Can you add instructions on replicating SQuAD results using just `pip install`? Just like Pyserini, there should be "Package Installation" instructions for people who want to use it and "Development Installation" instructions for people who want to develop... https://github.com/castorini/pyserini/

**Comment by MXueguang** [comment]
Sure.

**Comment by MXueguang** [comment]
fixed with PR https://github.com/rsvp-ai/bertserini/pull/7
